"""subject name

Revision ID: 20fe83844e42
Revises: 9630fc514832
Create Date: 2023-10-24 09:23:56.548026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20fe83844e42'
down_revision = '9630fc514832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
